### ISSUE TITLE
Karma not compatible with Silex 2.0

### ISSUE THREAD

**Issue by matracine** [Niktux/karma#97]
When trying to add karma to my project using silex 2.0 :

#composer require "niktux/karma" "~5.4"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for niktux/karma ~5.4 -> satisfiable by niktux/karma[5.4.0].
    - Conclusion: remove pimple/pimple v3.0.2
    - Conclusion: don't install pimple/pimple v3.0.2
    - niktux/karma 5.4.0 requires pimple/pimple ~1.1 -> satisfiable by pimple/pimple[v1.1.0, v1.1.1].
    - Can only install one of: pimple/pimple[v1.1.0, v3.0.2].
    - Can only install one of: pimple/pimple[v1.1.1, v3.0.2].
    - Installation request for pimple/pimple (locked at v3.0.2) -> satisfiable by pimple/pimple[v3.0.2].`

karma depends on pimple 1.1, Silex 2.0 uses pimple 3.0...
Mr Niktux, could you please upgrade ?

**Comment by Niktux** [comment]
Hi

Known issue. It's broken by design. See https://github.com/Niktux/karma/issues/84#issuecomment-137407392

If upgrade to silex 2.0, it will break for silex 1.0. Correct status is : Karma is an external tool, so it should not be retrieved by composer but must be standalone (like composer do)

Need time and energy to package it automatically as phar (successfully prototyped by killerwolf in PR#87)

**Comment by Niktux** [comment]
Duplicated with #84

**Comment by Niktux** [comment]
See #99

**Comment by Niktux** [comment]
Hi @matracine 

You can now use Karma with silex 2.0 projects or whatever
http://www.karma-php.com/gettingStarted.html#installation

Enjoy !
